/**
 *
 * This file holds configuration variables for gulp tasks.
 *
 */

exports.conf = {
  // Angular template cache configuration
  templateCache: {
    filename: 'views.js',
    options: {
      module: 'livraria',
      root: 'app'
    }
  },

  environment: {
    config: {
      file: 'config.json',
      dest: 'app',
      module: 'livraria.config'
    }
  },

  paths:{
    dist: 'dist/',
    src: 'app/',

    // HTML files configuration
    html: {
      files: 'app/**/*.html',
      index: 'app/index.html'
    },

    // Font files configuration
    fonts: {
      dist: {
        path: 'dist/fonts'
      },
      files: [
      ]
    },

    // JS Maps files configuration
    map: {
      dist: {
        path: '../maps/scripts' 
      }
    },

// Assets configuration
    // Image files configuration
    img: {
      dist: {
        path: 'dist/assets/img'
      },
      files: [
        'assets/img/**/*'
      ]
    },

    // Videos files configuration
    videos: {
      dist: {
        path: 'dist/assets/videos'
      },
      files: [
        'assets/videos/**/*'
      ]
    },

    // Other files configuration
    other: {
      dist:{
        path: 'dist/assets'
      },
      files: [
      ]
    },

    // CSS files configuration
    css: {
      dist: {
        path: 'dist/styles',
        app: 'app.min.css',
        vendor: 'vendor.min.css'
      },
      ignore:[
        '!app/index.css' // Generated by SCSS compilation
      ],
      other:{
      },
      app:[
        'app/**/*.css',
        'assets/css/**/*.css',
      ],
      vendor:[
      ]
    },

    // SCSS files configuration
    scss: {
        dist:{
          // Beware of placing it in a watched folder (can cause a loop in gulp)
          path: 'app' 
        },
        files:[
          'app/index.scss'
        ]
    },

    // Tests configuration
    test: {
      specs: 'app/**/*spec.js',
      files: [
        'app/index.module.js',
        'app/**/*.module.js',
        'app/**/*.js'
      ],
      vendor: [
        'node_modules/angular-mocks/angular-mocks.js'
      ],
      reporters: {
        coverage: {
          dest: 'coverage/',
          files: 'app/**/!(*spec).js'
        },
        html:{
          output: 'unit-tests-results.html',
          title: 'Portal da Transparência - Unit tests ',
          description: 'Resultado dos testes unitários do Controladoria nas escolas'
        }
      },
      templateCache: {
        module: 'views'
      }
    },

    // Js files configuration
    js: {
      all: [
        'app/**/*js'
      ],
      dist: {
        path:'dist/scripts'
      },
      app: [
        'app/index.module.js',
        'app/**/*.module.js',
        'app/**/*.js',
        '!app/**/*.spec.js'
      ],
      vendor: [
        'bower_components/jquery/dist/jquery.js',
        'bower_components/angular/angular.js',
        'bower_components/angular-route/angular-route.js'
      ]
    }
  }
}
