/**
 *
 * This file holds configuration variables for gulp tasks.
 *
 */

exports.conf = {
  // Angular template cache configuration
  templateCache: {
    filename: 'views.js',
    options: {
      module: 'cgescola',
      root: 'app'
    }
  },

  environment: {
    config: {
      file: 'config.json',
      dest: 'src/app',
      module: 'cgescola.config'
    }
  },

  paths:{
    dist: 'dist/',
    src: 'src/',

    // HTML files configuration
    html: {
      files: 'src/app/**/*.html',
      index: 'src/index.html'
    },

    // Font files configuration
    fonts: {
      dist: {
        path: 'dist/fonts'
      },
      files: [
        'bower_components/bootstrap/fonts/*.{eot,svg,ttf,woff,woff2}',
        'bower_components/material-design-iconic-font/fonts/*.{eot,svg,ttf,woff,woff2}',
        'bower_components/font-awesome/fonts/*.{eot,svg,ttf,woff,woff2}'
      ]
    },

    // JS Maps files configuration
    map: {
      dist: {
        path: '../maps/scripts' 
      }
    },

// Assets configuration
    // Image files configuration
    img: {
      dist: {
        path: 'dist/assets/img'
      },
      files: [
        'src/assets/img/**/*'
      ]
    },

    // Videos files configuration
    videos: {
      dist: {
        path: 'dist/assets/videos'
      },
      files: [
        'src/assets/videos/**/*'
      ]
    },

    // Other files configuration
    other: {
      dist:{
        path: 'dist/assets'
      },
      files: [
        'src/assets/jcs-auto-validate_pt-br.json'
      ]
    },

    // CSS files configuration
    css: {
      dist: {
        path: 'dist/styles',
        app: 'app.min.css',
        vendor: 'vendor.min.css'
      },
      ignore:[
        '!src/app/index.css' // Generated by SCSS compilation
      ],
      other:{
        highContrast: 'src/assets/css/highContrast.css'
      },
      app:[
        'src/app/**/*.css',
        'src/assets/css/**/*.css',
        '!src/assets/css/highContrast.css' // Injected dynamically
      ],
      vendor:[
        'src/assets/scriptsol/ol.css',
        //'bower_components/animate.css/animate.css',
        'bower_components/angular-loading-bar/build/loading-bar.css',
        'bower_components/angular-motion/dist/angular-motion.css',
        'bower_components/bootstrap-additions/dist/bootstrap-additions.min.css',
        'bower_components/c3/c3.css',
        'bower_components/material-design-iconic-font/css/material-design-iconic-font.css',
        'bower_components/ng-table/dist/ng-table.min.css',
        'bower_components/nouislider/distribute/jquery.nouislider.min.css',
        'bower_components/nouislider/distribute/jquery.nouislider.pips.min.css',
        'bower_components/bootstrap-css-only/css/bootstrap.css',
        'bower_components/textAngular/src/textAngular.css',
        'bower_components/angular-ui-select/dist/select.css',
        'bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css',
        'bower_components/datatables/media/css/jquery.dataTables.css',
        'bower_components/v-accordion/dist/v-accordion.css',
        'bower_components/font-awesome/css/font-awesome.min.css',,
        'bower_components/select2/dist/css/select2.min.css',
        'bower_components/angular-mass-autocomplete/massautocomplete.theme.css',
        'bower_components/AngularJS-Toaster/toaster.css',
        //'bower_components/angular-bootstrap-toggle-switch/style/bootstrap3/angular-toggle-switch-bootstrap-3.css',
        'node_modules/angular-bootstrap-datetimepicker/src/css/datetimepicker.css'
      ]
    },

    // SCSS files configuration
    scss: {
        dist:{
          // Beware of placing it in a watched folder (can cause a loop in gulp)
          path: 'src/app' 
        },
        files:[
          'src/app/index.scss'
        ]
    },

    // Tests configuration
    test: {
      specs: 'src/app/**/*spec.js',
      files: [
        'src/app/index.module.js',
        'src/app/**/*.module.js',
        'src/app/**/*.js'
      ],
      vendor: [
        'node_modules/angular-mocks/angular-mocks.js'
      ],
      reporters: {
        coverage: {
          dest: 'coverage/',
          files: 'src/app/**/!(*spec).js'
        },
        html:{
          output: 'unit-tests-results.html',
          title: 'Portal da Transparência - Unit tests ',
          description: 'Resultado dos testes unitários do Controladoria nas escolas'
        }
      },
      templateCache: {
        module: 'views'
      }
    },

    // Js files configuration
    js: {
      all: [
        'src/app/**/*js'
      ],
      dist: {
        path:'dist/scripts'
      },
      app: [
        'src/app/index.module.js',
        'src/app/**/*.module.js',
        'src/app/**/*.js',
        '!src/app/**/*.spec.js'
      ],
      vendor: [
        'bower_components/jquery/dist/jquery.js',
        'bower_components/angular/angular.js',
        //'bower_components/angular-animate/angular-animate.js',
        'bower_components/angular-cookies/angular-cookies.js',
        'bower_components/angular-touch/angular-touch.js',
        'bower_components/angular-sanitize/angular-sanitize.js',
        'bower_components/angular-messages/angular-messages.js',
        'bower_components/angular-aria/angular-aria.js',
        'bower_components/angular-resource/angular-resource.js',
        'bower_components/angular-ui-router/release/angular-ui-router.js',
        'bower_components/angular-route/angular-route.js',
        'bower_components/bootstrap-sass/assets/javascripts/bootstrap.js',
        //'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
        'bower_components/moment/moment.js',
        //'bower_components/angular-auto-validate/dist/jcs-auto-validate.js',
        'bower_components/angular-elastic/elastic.js',
        'bower_components/ng-file-upload/ng-file-upload.js',
        'bower_components/angular-loading-bar/build/loading-bar.js',
        'bower_components/angular-local-storage/dist/angular-local-storage.js',
        'bower_components/waypoints/waypoints.js',
        'bower_components/SHA-1/sha1.js',
        'bower_components/angulartics/src/angulartics.js',
        'bower_components/angulartics/src/angulartics-adobe.js',
        'bower_components/angulartics/src/angulartics-chartbeat.js',
        'bower_components/angulartics/src/angulartics-cnzz.js',
        'bower_components/angulartics/src/angulartics-flurry.js',
        'bower_components/angulartics/src/angulartics-ga-cordova.js',
        'bower_components/angulartics/src/angulartics-ga.js',
        'bower_components/angulartics/src/angulartics-gtm.js',
        'bower_components/angulartics/src/angulartics-kissmetrics.js',
        'bower_components/angulartics/src/angulartics-mixpanel.js',
        'bower_components/angulartics/src/angulartics-piwik.js',
        'bower_components/angulartics/src/angulartics-scroll.js',
        'bower_components/angulartics/src/angulartics-segmentio.js',
        'bower_components/angulartics/src/angulartics-splunk.js',
        'bower_components/angulartics/src/angulartics-woopra.js',
        'bower_components/angulartics/src/angulartics-marketo.js',
        'bower_components/angulartics/src/angulartics-intercom.js',
        'bower_components/ngSmoothScroll/angular-smooth-scroll.js',
        'bower_components/angular-strap/dist/angular-strap.js',
        'bower_components/angular-strap/dist/angular-strap.tpl.js',
        'bower_components/d3/d3.js',
        'bower_components/c3/c3.js',
        'bower_components/c3-angular/c3-angular.min.js',
        'bower_components/highcharts/highcharts.js',
        'bower_components/highcharts/highcharts-more.js',
        'bower_components/highcharts/modules/exporting.js',
        'bower_components/hammerjs/hammer.js',
        'bower_components/jquery-hammerjs/jquery.hammer.js',
        'bower_components/lodash/dist/lodash.compat.js',
        'bower_components/ng-table/dist/ng-table.min.js',
        'bower_components/nouislider/distribute/jquery.nouislider.all.min.js',
        'bower_components/rangy/rangy-core.min.js',
        'bower_components/rangy/rangy-cssclassapplier.min.js',
        'bower_components/rangy/rangy-selectionsaverestore.min.js',
        'bower_components/rangy/rangy-serializer.min.js',
        'bower_components/textAngular/src/textAngular.js',
        'bower_components/textAngular/src/textAngular-sanitize.js',
        'bower_components/textAngular/src/textAngularSetup.js',
        'bower_components/angular-ui-select/dist/select.js',
        'bower_components/velocity/velocity.js',
        'bower_components/velocity/velocity.ui.js',
        'bower_components/bootstrap3-typeahead/bootstrap3-typeahead.js',
        'bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js',
        'bower_components/datatables/media/js/jquery.dataTables.js',
        'bower_components/bootstrap-validator/dist/validator.min.js',
        'bower_components/underscore/underscore.js',
        'bower_components/angular-underscore-module/angular-underscore-module.js',
        'bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js',
        'bower_components/blob-polyfill/Blob.js',
        'bower_components/file-saver.js/FileSaver.js',
        'bower_components/angular-file-saver/dist/angular-file-saver.bundle.js',
        'bower_components/checklist-model/checklist-model.js',
        'bower_components/v-accordion/dist/v-accordion.js',
        'bower_components/angularjs-socialshare/dist/angular-socialshare.min.js',
        'bower_components/angular-ui-mask/dist/mask.js',
        'bower_components/ngstorage/ngStorage.js',
        'bower_components/select2/dist/js/select2.js',
        'bower_components/ngMask/dist/ngMask.js',
        'src/assets/scriptsol/ol.js',
        'bower_components/highcharts/modules/treemap.js',
        //'bower_components/angular-bootstrap-toggle-switch/angular-toggle-switch.min.js',
        'bower_components/angular-css/angular-css.min.js',
        //'node_modules/angular-bootstrap-datetimepicker/src/js/datetimepicker.js',
        'node_modules/angular-date-time-input/src/dateTimeInput.js',
        'bower_components/angular-crumble/crumble.js',
        'bower_components/angular-file-model/angular-file-model.js',
        'bower_components/moment/locale/pt-br.js',
        'bower_components/angular-mass-autocomplete/massautocomplete.js',
        'bower_components/angular-bootstrap-multiselect/dist/angular-bootstrap-multiselect.js',
        'bower_components/AngularJS-Toaster/toaster.js',
        'bower_components/angularUtils-pagination/dirPagination.js'
      ]
    }
  }
}
